AWSTemplateFormatVersion: "2010-09-09"
Description: countries-visited-backend
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 180

Resources:
  handler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/index.handler
      Runtime: nodejs16.x
      MemorySize: 128
      Description: Main handler that routes to other functions.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "countries-visited-table"
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
